In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [5]:
import numpy as np

In [7]:
webpage=requests.get("https://www.screener.in/screens/29729/top-1000-stocks/?page=1")

In [13]:
soup=BeautifulSoup(webpage.text,'lxml')
print(soup)

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Top 1000 stocks - Screener</title>
<!-- plausible -->
<script data-domain="screener.in" defer="" event-user="unregistered" src="https://plausible.screener.in/js/script.pageview-props.tagged-events.js"></script>
<script>window.plausible = window.plausible || function () { (window.plausible.q = window.plausible.q || []).push(arguments) }</script>
<!-- FONT -->
<link href="https://cdn-static.screener.in/inter/inter.43d4904a3137.css" rel="stylesheet"/>
<link href="https://cdn-static.screener.in/fontello/css/fontello.3d9a3b82e52a.css" rel="stylesheet"/>
<!-- CSS -->
<link href="https://cdn-static.screener.in/css/normalize.a2444750a947.css" media="all" rel="stylesheet"/>
<link href="https://cdn-static.screener.in/css/skeleton.eb869285cb83.css" media="all" rel="stylesheet"/>
<link href="https://cdn-static.screener.in/css/custom.99bee5d0e235.css" media="all" rel="stylesheet"/>
<meta content="Mittal Analytics Private Limited" name="author"/>
<!-- PWA manifest -->
<meta content="#fff" media="(prefers-color-scheme: light)" name="theme-color"/>
<meta content="#222530" media="(prefers-color-scheme: dark)" name="theme-color"/>
<link href="/static/manifest.json" rel="manifest"/>
<!-- favicons -->
<link href="https://cdn-static.screener.in/favicon/apple-touch-icon.b6e5f24bf7d3.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://cdn-static.screener.in/favicon/favicon-32x32.00205914303a.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="https://cdn-static.screener.in/favicon/favicon-16x16.2b35594b2f33.png" rel="icon" sizes="16x16" type="image/png"/>
<link color="#8ED443" href="https://cdn-static.screener.in/favicon/safari-pinned-tab.adbe3ed3c5ad.svg" rel="mask-icon"/>
<meta content="#da532c" name="msapplication-TileColor"/>
</head>
<body class="light flex-column">
<nav class="u-full-width no-print">
<div id="mobile-search"><div class="has-addon left-addon dropdown-typeahead">
<i class="addon icon-search"></i>
<input aria-label="Search for a company" autocomplete="off" class="u-full-width" data-company-search="true" placeholder="Search for a company" spellcheck="false" type="search"/>
</div>
</div>
<ul class="bottom-menu-bar hide-from-tablet-landscape">
<li class="">
<a href="/">
<i class="icon-home"></i>
<br/>
        Home
      </a>
</li>
<li class="">
<a href="/explore/">
<i class="icon-screens"></i>
<br/>
      Screens
    </a>
</li>
<li>
<button class="search-button" onclick="MobileMenu.toggleSearch(this)" title="Search" type="button">
<i class="icon-search" style="font-size: 18px"></i>
</button>
</li>
<li>
<button class="button-plain" onclick="Modal.showInModal('#nav-tools-menu')">
<i class="icon-tools"></i>
<br/>
      Tools
    </button>
</li>
<li class="">
<a href="/register/?page=1">
<i class="icon-user-plus"></i>
<br/>
        Login
      </a>
</li>
</ul>
<div class="top-nav-holder">
<div class="container">
<div class="layer-holder top-navigation">
<div class="layer flex flex-space-between" style="align-items: center;
              height: 50px">
<div class="flex" style="align-items: center">
<a class="logo-holder" href="/">
<img alt="Screener Logo" class="logo" src="https://cdn-static.screener.in/img/logo-black.f44abb4998d1.svg"/>
</a>
<div class="desktop-links" style="margin-left: 48px">
<a href="/">

            Home

        </a>
<a href="/explore/">Screens</a>
<div class="dropdown-menu">
<button class="button-plain" onclick="Utils.toggleDropdown(event)" type="button">
            Tools
            <i class="icon-down"></i>
</button>
<ul class="dropdown-content flex-column tools-menu" id="nav-tools-menu" style="width: 350px">
<li>
<a class="flex flex-align-center flex-gap-16" href="/screen/new/">
<div class="bg-stripes square-56">
<img alt="Create a stock screen" src="https://cdn-static.screener.in/icons/screens.e960a5daedf9.svg"/>
</div>
<div>
<div class="font-weight-500 font-size-14">Create a stock screen</div>
<div class="sub font-size-13">Run queries on 10 years of financial data</div>
</div>
</a>
</li>
<li class="flex flex-align-center no-hover" style="padding: 4px 0;">
<div class="button button-primary premium-indicator flex flex-align-center">
<img alt="Premium icon" src="https://cdn-static.screener.in/icons/crown.fb0d2413ee43.svg" style="margin-right: 8px"/>
<span>Premium features</span>
</div>
<hr class="flex-grow" style="padding: 0; margin: 0;"/>
</li>
<li>
<a class="flex flex-align-center flex-gap-16" href="/hs/">
<div class="bg-stripes square-56">
<img alt="Commodity Prices" src="https://cdn-static.screener.in/icons/export.d623f0029933.svg"/>
</div>
<div>
<div class="font-weight-500 font-size-14">Commodity Prices</div>
<div class="sub font-size-13">See prices and trends of over 10,000 commodities</div>
</div>
</a>
</li>
<li>
<a class="flex flex-align-center flex-gap-16" href="/people/">
<div class="bg-stripes square-56">
<img alt="Search shareholders by name" src="https://cdn-static.screener.in/icons/shares.10acc20cb936.svg"/>
</div>
<div>
<div class="font-weight-500 font-size-14">Search shareholders</div>
<div class="sub font-size-13">See companies where a person holds over 1% of the shares</div>
</div>
</a>
</li>
<li>
<a class="flex flex-align-center flex-gap-16" href="/announcements/">
<div class="bg-stripes square-56">
<img alt="Latest Announcements" src="https://cdn-static.screener.in/icons/loudspeaker.88769927f6eb.svg"/>
</div>
<div>
<div class="font-weight-500 font-size-14">Latest Announcements</div>
<div class="sub font-size-13">Browse, filter and set alerts for announcements.</div>
</div>
</a>
</li>
<li style="padding: 16px;">
<a class="button button-primary text-align-center" href="/premium/?driver=top-nav-tools" style="color: var(--white);
                          padding: 10px 24px">Upgrade to premium</a>
</li>
</ul>
</div>
</div>
</div>
<div class="show-from-tablet-landscape flex flex-gap-16" style="justify-content: flex-end;
                flex: 1 1 400px">
<div class="search" id="desktop-search"><div class="has-addon left-addon dropdown-typeahead">
<i class="addon icon-search"></i>
<input aria-label="Search for a company" autocomplete="off" class="u-full-width" data-company-search="true" placeholder="Search for a company" spellcheck="false" type="search"/>
</div>
</div>
<div class="flex flex-gap-8" style="margin: 4px">
<a class="button account" href="/login/?page=1">
<i class="icon-user-line blue-icon"></i>
            Login
          </a>
<a class="button account button-secondary" href="/register/?page=1">Get free account</a>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<main class="flex-grow container">
<div class="breadcrumb hidden-if-empty"></div>
<div class="card card-large">
<div class="flex-row flex-space-between flex-gap-8 margin-bottom-16" data-screen-id="29729" id="screen-info">
<h1 class="margin-0">

    Top 1000 stocks

  </h1>
<div class="flex flex-gap-8 flex-end flex-align-center">
<form action="/alerts/add-screen-29729/" method="POST">
<input name="csrfmiddlewaretoken" type="hidden" value="6BJU2xEWso421W8CmXjcfmpI7QSEEm1wQNfZkVYUunCFw4TuHApF8i1XJwtaRWco"/>
<button class="button-primary" type="submit">
<i class="icon-bell"></i> Get Email Updates
        </button>
</form>
</div>
</div>
<div style="max-width: 750px">
<p>a</p>
<p class="sub">
    by <a href="/user/3381/">Vatsal Bavishi</a>
</p>
</div>
<div data-messages=""></div>
<div class="flex-row flex-gap-8 flex-space-between flex-align-center">
<div class="sub" data-page-info="">
      1585 results found: Showing page 1 of 64
    </div>
<div class="flex flex-gap-8 flex-end">
<div class="dropdown-filter">
<button class="button-small plausible-event-name=Industry+Filter plausible-event-user=unregistered" data-api-url="/api/get/sectors/?page=1&amp;url_name=screen&amp;screen_id=29729&amp;slug_name=top-1000-stocks" onclick="toggleIndustryFilter(event)">
<i class="icon-funnel"></i>
          Industry
        </button>
<ul class="dropdown-content font-size-14" style="min-width: 225px;">
</ul>
</div>
<script src="https://cdn-static.screener.in/js/industry-filter.5f299c25b014.js"></script>
<form action="/api/export/screen/?page=1&amp;url_name=screen&amp;screen_id=29729&amp;slug_name=top-1000-stocks" class="hide-on-mobile" method="POST">
<input name="csrfmiddlewaretoken" type="hidden" value="6BJU2xEWso421W8CmXjcfmpI7QSEEm1wQNfZkVYUunCFw4TuHApF8i1XJwtaRWco"/>
<button aria-label="Download Results" class="button-small tooltip-left plausible-event-name=Excel+Screen plausible-event-user=unregistered" data-tooltip="Download Results" type="submit">
<i class="icon-download"></i>
          Export
        </button>
</form>
<a class="button button-small button-secondary plausible-event-name=Edit+Columns plausible-event-user=unregistered" href="/user/columns/?next=/screens/29729/top-1000-stocks/%3Fpage%3D1">
<i class="icon-cog"></i>
        Edit Columns
      </a>
</div>
</div>
<div class="responsive-holder fill-card-width" data-page-results="">
<table class="data-table text-nowrap striped mark-visited no-scroll-right">
<tbody>
<tr>
<th class="text" scope="colgroup">
<a aria-label="Default Sort" class="" href="?order=asc">S.No.</a>
</th>
<th class="text" scope="colgroup">
<a aria-label="Sort on Name" class="" href="?sort=name&amp;order=desc">Name</a>
</th>
<th data-tooltip="Current Price" scope="colgroup">
<a aria-label="Sort on Current Price" class="" href="?sort=current+price&amp;order=desc">
                    CMP
                    <span style="color: hsl(0, 0%, 45%)">Rs.</span>
</a>
</th>
<th data-tooltip="Price to Earning" scope="colgroup">
<a aria-label="Sort on Price to Earning" class="" href="?sort=price+to+earning&amp;order=desc">
                    P/E
                    <span style="color: hsl(0, 0%, 45%)"></span>
</a>
</th>
<th data-tooltip="Market Capitalization" scope="colgroup">
<a aria-label="Sort on Market Capitalization" class="desc" href="?sort=market+capitalization&amp;order=desc">
                    Mar Cap
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="Dividend yield" scope="colgroup">
<a aria-label="Sort on Dividend yield" class="" href="?sort=dividend+yield&amp;order=desc">
                    Div Yld
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Net Profit latest quarter" scope="colgroup">
<a aria-label="Sort on Net Profit latest quarter" class="" href="?sort=net+profit+latest+quarter&amp;order=desc">
                    NP Qtr
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="YOY Quarterly profit growth" scope="colgroup">
<a aria-label="Sort on YOY Quarterly profit growth" class="" href="?sort=yoy+quarterly+profit+growth&amp;order=desc">
                    Qtr Profit Var
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Sales latest quarter" scope="colgroup">
<a aria-label="Sort on Sales latest quarter" class="" href="?sort=sales+latest+quarter&amp;order=desc">
                    Sales Qtr
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="YOY Quarterly sales growth" scope="colgroup">
<a aria-label="Sort on YOY Quarterly sales growth" class="" href="?sort=yoy+quarterly+sales+growth&amp;order=desc">
                    Qtr Sales Var
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Return on capital employed" scope="colgroup">
<a aria-label="Sort on Return on capital employed" class="" href="?sort=return+on+capital+employed&amp;order=desc">
                    ROCE
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Profit after tax last year" scope="colgroup">
<a aria-label="Sort on Profit after tax last year" class="" href="?sort=profit+after+tax+last+year&amp;order=desc">
                    PAT Ann
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
</tr>
<tr data-row-company-id="2726">
<td class="text">1.</td>
<td class="text">
<a href="/company/RELIANCE/consolidated/" target="_blank">Reliance Industr</a>
</td>
<td>1272.65</td><td>24.99</td><td>1722197.03</td><td>0.39</td><td>21930.00</td><td>7.38</td><td>239986.00</td><td>6.62</td><td>9.61</td><td>69797.17</td>
</tr>
<tr data-row-company-id="1298">
<td class="text">2.</td>
<td class="text">
<a href="/company/HDFCBANK/consolidated/" target="_blank">HDFC Bank</a>
</td>
<td>1805.45</td><td>19.89</td><td>1381515.91</td><td>1.07</td><td>18340.11</td><td>2.31</td><td>85040.17</td><td>9.01</td><td>7.67</td><td>63902.06</td>
</tr>
<tr data-row-company-id="3365">
<td class="text">3.</td>
<td class="text">
<a href="/company/TCS/consolidated/" target="_blank">TCS</a>
</td>
<td>3638.00</td><td>26.98</td><td>1316260.18</td><td>1.49</td><td>12444.00</td><td>5.16</td><td>63973.00</td><td>5.60</td><td>64.28</td><td>46598.19</td>
</tr>
<tr data-row-company-id="467">
<td class="text">4.</td>
<td class="text">
<a href="/company/BHARTIARTL/consolidated/" target="_blank">Bharti Airtel</a>
</td>
<td>1736.75</td><td>52.10</td><td>1040575.36</td><td>0.46</td><td>16134.60</td><td>230.71</td><td>45129.30</td><td>19.08</td><td>13.13</td><td>11911.52</td>
</tr>
<tr data-row-company-id="1384">
<td class="text">5.</td>
<td class="text">
<a href="/company/ICICIBANK/consolidated/" target="_blank">ICICI Bank</a>
</td>
<td>1335.20</td><td>19.21</td><td>943441.54</td><td>0.74</td><td>13846.89</td><td>16.56</td><td>47037.12</td><td>15.10</td><td>7.60</td><td>44246.06</td>
</tr>
<tr data-row-company-id="3188">
<td class="text">6.</td>
<td class="text">
<a href="/company/SBIN/consolidated/" target="_blank">St Bk of India</a>
</td>
<td>764.20</td><td>8.70</td><td>682019.50</td><td>1.78</td><td>19483.78</td><td>17.27</td><td>124653.66</td><td>10.44</td><td>6.16</td><td>67102.23</td>
</tr>
<tr data-row-company-id="1489">
<td class="text">7.</td>
<td class="text">
<a href="/company/INFY/consolidated/" target="_blank">Infosys</a>
</td>
<td>1599.40</td><td>24.09</td><td>664188.19</td><td>2.36</td><td>6822.00</td><td>11.46</td><td>41764.00</td><td>7.58</td><td>39.99</td><td>26025.25</td>
</tr>
<tr data-row-company-id="372">
<td class="text">8.</td>
<td class="text">
<a href="/company/BAJFINANCE/consolidated/" target="_blank">Bajaj Finance</a>
</td>
<td>8864.80</td><td>34.38</td><td>549510.07</td><td>0.40</td><td>4308.19</td><td>16.70</td><td>18035.11</td><td>27.33</td><td>11.92</td><td>14460.49</td>
</tr>
<tr data-row-company-id="1350">
<td class="text">9.</td>
<td class="text">
<a href="/company/HINDUNILVR/consolidated/" target="_blank">Hind. Unilever</a>
</td>
<td>2239.25</td><td>50.87</td><td>526132.23</td><td>1.86</td><td>2989.00</td><td>2.93</td><td>15818.00</td><td>1.61</td><td>27.24</td><td>10272.57</td>
</tr>
<tr data-row-company-id="1552">
<td class="text">10.</td>
<td class="text">
<a href="/company/ITC/consolidated/" target="_blank">ITC</a>
</td>
<td>408.35</td><td>25.79</td><td>511014.09</td><td>3.39</td><td>5013.18</td><td>-8.40</td><td>18790.17</td><td>9.28</td><td>37.47</td><td>20422.35</td>
</tr>
<tr data-row-company-id="1275221">
<td class="text">11.</td>
<td class="text">
<a href="/company/LICI/consolidated/" target="_blank">Life Insurance</a>
</td>
<td>786.00</td><td>11.61</td><td>497144.72</td><td>1.27</td><td>11008.68</td><td>16.69</td><td>203751.32</td><td>-4.81</td><td>72.95</td><td>40915.85</td>
</tr>
<tr data-row-company-id="1870">
<td class="text">12.</td>
<td class="text">
<a href="/company/LT/consolidated/" target="_blank">Larsen &amp; Toubro</a>
</td>
<td>3430.35</td><td>34.16</td><td>471733.12</td><td>0.81</td><td>3973.98</td><td>13.96</td><td>64667.78</td><td>17.31</td><td>13.44</td><td>12899.15</td>
</tr>
<tr data-row-company-id="1297">
<td class="text">13.</td>
<td class="text">
<a href="/company/HCLTECH/consolidated/" target="_blank">HCL Technologies</a>
</td>
<td>1632.90</td><td>25.98</td><td>443114.40</td><td>3.31</td><td>4594.00</td><td>5.54</td><td>29890.00</td><td>5.08</td><td>29.60</td><td>15573.20</td>
</tr>
<tr data-row-company-id="1818">
<td class="text">14.</td>
<td class="text">
<a href="/company/KOTAKBANK/consolidated/" target="_blank">Kotak Mah. Bank</a>
</td>
<td>2139.50</td><td>21.65</td><td>425380.33</td><td>0.09</td><td>4701.02</td><td>10.23</td><td>16633.14</td><td>14.75</td><td>7.86</td><td>18207.83</td>
</tr>
<tr data-row-company-id="3245">
<td class="text">15.</td>
<td class="text">
<a href="/company/SUNPHARMA/consolidated/" target="_blank">Sun Pharma.Inds.</a>
</td>
<td>1759.40</td><td>35.82</td><td>422139.02</td><td>0.76</td><td>2912.98</td><td>22.66</td><td>13675.46</td><td>10.46</td><td>17.32</td><td>9988.74</td>
</tr>
<tr>
<th class="text" scope="colgroup">
<a aria-label="Default Sort" class="" href="?order=asc">S.No.</a>
</th>
<th class="text" scope="colgroup">
<a aria-label="Sort on Name" class="" href="?sort=name&amp;order=desc">Name</a>
</th>
<th data-tooltip="Current Price" scope="colgroup">
<a aria-label="Sort on Current Price" class="" href="?sort=current+price&amp;order=desc">
                    CMP
                    <span style="color: hsl(0, 0%, 45%)">Rs.</span>
</a>
</th>
<th data-tooltip="Price to Earning" scope="colgroup">
<a aria-label="Sort on Price to Earning" class="" href="?sort=price+to+earning&amp;order=desc">
                    P/E
                    <span style="color: hsl(0, 0%, 45%)"></span>
</a>
</th>
<th data-tooltip="Market Capitalization" scope="colgroup">
<a aria-label="Sort on Market Capitalization" class="desc" href="?sort=market+capitalization&amp;order=desc">
                    Mar Cap
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="Dividend yield" scope="colgroup">
<a aria-label="Sort on Dividend yield" class="" href="?sort=dividend+yield&amp;order=desc">
                    Div Yld
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Net Profit latest quarter" scope="colgroup">
<a aria-label="Sort on Net Profit latest quarter" class="" href="?sort=net+profit+latest+quarter&amp;order=desc">
                    NP Qtr
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="YOY Quarterly profit growth" scope="colgroup">
<a aria-label="Sort on YOY Quarterly profit growth" class="" href="?sort=yoy+quarterly+profit+growth&amp;order=desc">
                    Qtr Profit Var
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Sales latest quarter" scope="colgroup">
<a aria-label="Sort on Sales latest quarter" class="" href="?sort=sales+latest+quarter&amp;order=desc">
                    Sales Qtr
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
<th data-tooltip="YOY Quarterly sales growth" scope="colgroup">
<a aria-label="Sort on YOY Quarterly sales growth" class="" href="?sort=yoy+quarterly+sales+growth&amp;order=desc">
                    Qtr Sales Var
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Return on capital employed" scope="colgroup">
<a aria-label="Sort on Return on capital employed" class="" href="?sort=return+on+capital+employed&amp;order=desc">
                    ROCE
                    <span style="color: hsl(0, 0%, 45%)">%</span>
</a>
</th>
<th data-tooltip="Profit after tax last year" scope="colgroup">
<a aria-label="Sort on Profit after tax last year" class="" href="?sort=profit+after+tax+last+year&amp;order=desc">
                    PAT Ann
                    <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
</a>
</th>
</tr>
<tr data-row-company-id="2023">
<td class="text">16.</td>
<td class="text">
<a href="/company/MARUTI/consolidated/" target="_blank">Maruti Suzuki</a>
</td>

In [43]:
t=soup.find_all('td',class_='text')

In [47]:
a=1
for i in t:
    if a%2!=0:
        print(i.text)
    else :
        print(i.find('a').text)
    a+=1

1.
Reliance Industr
2.
HDFC Bank
3.
TCS
4.
Bharti Airtel
5.
ICICI Bank
6.
St Bk of India
7.
Infosys
8.
Bajaj Finance
9.
Hind. Unilever
10.
ITC
11.
Life Insurance
12.
Larsen & Toubro
13.
HCL Technologies
14.
Kotak Mah. Bank
15.
Sun Pharma.Inds.
16.
Maruti Suzuki
17.
NTPC
18.
M & M
19.
Axis Bank
20.
UltraTech Cem.
21.
Bajaj Finserv
22.
O N G C
23.
Wipro
24.
Hind.Aeronautics
25.
Titan Company

In [107]:
soup.find('div',class_="responsive-holder fill-card-width").find_all('tr')[26].find_all('td')[11].text

'3496.00'

In [123]:
soup.find('div',class_="responsive-holder fill-card-width").find_all('tr')[26].find_all('td')[1].text.strip()

'Titan Company'

In [129]:
s=soup.find('div',class_="responsive-holder fill-card-width")

In [167]:
s_no=[]
name=[]
current_price=[]
price_to_earn=[]
market_capitalization=[]
dividend_yield=[]
Net_Profit_latest_quarter=[]
YOY_Quarterly_profit_growth=[]
Sales_latest_quarter=[]
YOY_Quarterly_sales_growth=[]
Return_on_capital_employed=[]
Profit_after_tax_last_year=[]

for i in range(1,27):
    if i==16:
        continue
    s_no.append(s.find_all('tr')[i].find_all('td')[0].text.strip())
    name.append(s.find_all('tr')[i].find_all('td')[1].text.strip())
    current_price.append(s.find_all('tr')[i].find_all('td')[2].text.strip())
    price_to_earn.append(s.find_all('tr')[i].find_all('td')[3].text.strip())
    market_capitalization.append(s.find_all('tr')[i].find_all('td')[4].text.strip())
    dividend_yield.append(s.find_all('tr')[i].find_all('td')[5].text.strip())
    Net_Profit_latest_quarter.append(s.find_all('tr')[i].find_all('td')[6].text.strip())
    YOY_Quarterly_profit_growth.append(s.find_all('tr')[i].find_all('td')[7].text.strip())
    Sales_latest_quarter.append(s.find_all('tr')[i].find_all('td')[8].text.strip())
    YOY_Quarterly_sales_growth.append(s.find_all('tr')[i].find_all('td')[9].text.strip())
    Return_on_capital_employed.append(s.find_all('tr')[i].find_all('td')[10].text.strip())
    Profit_after_tax_last_year.append(s.find_all('tr')[i].find_all('td')[11].text.strip())

page1=pd.DataFrame({"s_no":s_no,
"name":name,
"current_price(Rs)":current_price,
"price_to_earn":price_to_earn,
"market_capitalization(Rs.Cr.)":market_capitalization,
"dividend_yield(%)":dividend_yield,
"Net_Profit_latest_quarter(Rs.Cr.)":Net_Profit_latest_quarter,
"YOY_Quarterly_profit_growth(%)":YOY_Quarterly_profit_growth,
"Sales_latest_quarter(Rs.Cr.)":Sales_latest_quarter,
"YOY_Quarterly_sales_growth(%)":YOY_Quarterly_sales_growth,
"Return_on_capital_employed(%)":Return_on_capital_employed,
"Profit_after_tax_last_year(Rs.Cr.)":Profit_after_tax_last_year,})

In [169]:
page1

,s_no,name,current_price(Rs),price_to_earn,market_capitalization(Rs.Cr.),dividend_yield(%),Net_Profit_latest_quarter(Rs.Cr.),YOY_Quarterly_profit_growth(%),Sales_latest_quarter(Rs.Cr.),YOY_Quarterly_sales_growth(%),Return_on_capital_employed(%),Profit_after_tax_last_year(Rs.Cr.)
0,1.,Reliance Industr,1272.65,24.99,1722197.03,0.39,21930.00,7.38,239986.00,6.62,9.61,69797.17
1,2.,HDFC Bank,1805.45,19.89,1381515.91,1.07,18340.11,2.31,85040.17,9.01,7.67,63902.06
2,3.,TCS,3638.00,26.98,1316260.18,1.49,12444.00,5.16,63973.00,5.60,64.28,46598.19
3,4.,Bharti Airtel,1736.75,52.10,1040575.36,0.46,16134.60,230.71,45129.30,19.08,13.13,11911.52
4,5.,ICICI Bank,1335.20,19.21,943441.54,0.74,13846.89,16.56,47037.12,15.10,7.60,44246.06
5,6.,St Bk of India,764.20,8.70,682019.50,1.78,19483.78,17.27,124653.66,10.44,6.16,67102.23
6,7.,Infosys,1599.40,24.09,664188.19,2.36,6822.00,11.46,41764.00,7.58,39.99,26025.25
7,8.,Bajaj Finance,8864.80,34.38,549510.07,0.40,4308.19,16.70,18035.11,27.33,11.92,14460.49
8,9.,Hind. Unilever,2239.25,50.87,526132.23,1.86,2989.00,2.93,15818.00,1.61,27.24,10272.57
9,10.,ITC,408.35,25.79,511014.09,3.39,5013.18,-8.40,18790.17,9.28,37.47,20422.35
10,11.,Life Insurance,786.00,11.61,497144.72,1.27,11008.68,16.69,203751.32,-4.81,72.95,40915.85
11,12.,Larsen & Toubro,3430.35,34.16,471733.12,0.81,3973.98,13.96,64667.78,17.31,13.44,12899.15
12,13.,HCL Technologies,1632.90,25.98,443114.40,3.31,4594.00,5.54,29890.00,5.08,29.60,15573.20
13,14.,Kotak Mah. Bank,2139.50,21.65,425380.33,0.09,4701.02,10.23,16633.14,14.75,7.86,18207.83
14,15.,Sun Pharma.Inds.,1759.40,35.82,422139.02,0.76,2912.98,22.66,13675.46,10.46,17.32,9988.74
15,16.,Maruti Suzuki,11731.00,25.42,368825.64,1.05,3726.90,16.22,38764.30,15.67,21.82,13495.86
16,17.,NTPC,355.35,15.71,344571.01,2.16,5169.69,-1.80,45052.82,5.21,10.47,20959.27
17,18.,M & M,2750.30,27.60,342007.80,0.76,3624.48,19.64,41470.05,17.48,13.58,11268.64
18,19.,Axis Bank,1093.15,12.10,338516.19,0.09,6778.91,3.86,32162.20,11.42,7.06,26389.51
19,20.,UltraTech Cem.,11413.05,52.52,329498.36,0.61,1473.51,-17.20,17193.33,2.71,15.12,6984.22
20,21.,Bajaj Finserv,1943.30,36.22,310279.38,0.05,4411.89,3.40,32041.81,10.34,11.72,8152.51
21,22.,O N G C,239.60,7.64,301423.46,5.14,9783.64,-17.97,166096.68,-0.75,18.43,50218.43
22,23.,Wipro,267.65,22.63,280279.22,2.21,3366.70,24.48,22318.80,0.51,16.93,10889.74
23,24.,Hind.Aeronautics,4136.40,31.96,276632.11,0.84,1432.60,14.29,6956.93,14.78,38.88,7590.82
24,25.,Titan Company,3049.80,83.57,270757.02,0.36,1047.00,-0.57,17740.00,25.25,22.70,3496.00

In [177]:
final=pd.DataFrame()
for x in range(1,61):
    webpage=requests.get("https://www.screener.in/screens/29729/top-1000-stocks/?page={}".format(x)).text
    soup=BeautifulSoup(webpage,'lxml')
    s=soup.find('div',class_="responsive-holder fill-card-width")
    s_no=[]
    name=[]
    current_price=[]
    price_to_earn=[]
    market_capitalization=[]
    dividend_yield=[]
    Net_Profit_latest_quarter=[]
    YOY_Quarterly_profit_growth=[]
    Sales_latest_quarter=[]
    YOY_Quarterly_sales_growth=[]
    Return_on_capital_employed=[]
    Profit_after_tax_last_year=[]
    
    for i in range(1,27):
        if i==16:
            continue
        s_no.append(s.find_all('tr')[i].find_all('td')[0].text.strip())
        name.append(s.find_all('tr')[i].find_all('td')[1].text.strip())
        current_price.append(s.find_all('tr')[i].find_all('td')[2].text.strip())
        price_to_earn.append(s.find_all('tr')[i].find_all('td')[3].text.strip())
        market_capitalization.append(s.find_all('tr')[i].find_all('td')[4].text.strip())
        dividend_yield.append(s.find_all('tr')[i].find_all('td')[5].text.strip())
        Net_Profit_latest_quarter.append(s.find_all('tr')[i].find_all('td')[6].text.strip())
        YOY_Quarterly_profit_growth.append(s.find_all('tr')[i].find_all('td')[7].text.strip())
        Sales_latest_quarter.append(s.find_all('tr')[i].find_all('td')[8].text.strip())
        YOY_Quarterly_sales_growth.append(s.find_all('tr')[i].find_all('td')[9].text.strip())
        Return_on_capital_employed.append(s.find_all('tr')[i].find_all('td')[10].text.strip())
        Profit_after_tax_last_year.append(s.find_all('tr')[i].find_all('td')[11].text.strip())
    
    page=pd.DataFrame({"s_no":s_no,
    "name":name,
    "current_price(Rs)":current_price,
    "price_to_earn":price_to_earn,
    "market_capitalization(Rs.Cr.)":market_capitalization,
    "dividend_yield(%)":dividend_yield,
    "Net_Profit_latest_quarter(Rs.Cr.)":Net_Profit_latest_quarter,
    "YOY_Quarterly_profit_growth(%)":YOY_Quarterly_profit_growth,
    "Sales_latest_quarter(Rs.Cr.)":Sales_latest_quarter,
    "YOY_Quarterly_sales_growth(%)":YOY_Quarterly_sales_growth,
    "Return_on_capital_employed(%)":Return_on_capital_employed,
    "Profit_after_tax_last_year(Rs.Cr.)":Profit_after_tax_last_year,})
    final = pd.concat([final, page], ignore_index=True)
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60

In [179]:
final

,s_no,name,current_price(Rs),price_to_earn,market_capitalization(Rs.Cr.),dividend_yield(%),Net_Profit_latest_quarter(Rs.Cr.),YOY_Quarterly_profit_growth(%),Sales_latest_quarter(Rs.Cr.),YOY_Quarterly_sales_growth(%),Return_on_capital_employed(%),Profit_after_tax_last_year(Rs.Cr.)
0,1.,Reliance Industr,1272.55,25.00,1722061.70,0.39,21930.00,7.38,239986.00,6.62,9.61,69797.17
1,2.,HDFC Bank,1805.95,19.90,1381898.48,1.07,18340.11,2.31,85040.17,9.01,7.67,63902.06
2,3.,TCS,3635.50,26.95,1315355.65,1.49,12444.00,5.16,63973.00,5.60,64.28,46598.19
3,4.,Bharti Airtel,1733.00,51.98,1038328.55,0.46,16134.60,230.71,45129.30,19.08,13.13,11911.52
4,5.,ICICI Bank,1335.40,19.20,943582.86,0.74,13846.89,16.56,47037.12,15.10,7.60,44246.06
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,1496.,Aryaman Fin.Serv,508.50,24.59,594.03,0.00,21.61,175.97,37.58,124.63,25.80,17.65
1496,1497.,SBC Exports,12.45,35.09,592.94,0.27,3.27,15.14,50.02,4.62,24.52,9.39
1497,1498.,Madhuveer Com,241.50,757.96,591.20,0.02,0.99,4850.00,2.28,4460.00,13.49,2.34
1498,1499.,Permanent Magnet,685.00,35.33,589.11,0.27,2.04,-46.88,49.35,-2.34,,19.15
1499,1500.,Delton Cables,680.00,52.89,587.51,0.21,3.36,19.57,188.64,72.01,18.71,9.72

In [181]:
del final['s_no']

In [185]:
final.to_csv('top_1500_stock.csv')

In [193]:
final.describe()

,name,current_price(Rs),price_to_earn,market_capitalization(Rs.Cr.),dividend_yield(%),Net_Profit_latest_quarter(Rs.Cr.),YOY_Quarterly_profit_growth(%),Sales_latest_quarter(Rs.Cr.),YOY_Quarterly_sales_growth(%),Return_on_capital_employed(%),Profit_after_tax_last_year(Rs.Cr.)
count,1500,1500,1500,1500,1500,1500,1500,1500,1500,1500,1500
unique,1500,1478,1316,1499,299,1413,1434,1493,1323,1192,1474
top,Reliance Industr,57.00,,1246.00,0.00,0.53,,0.00,,,36.44
freq,1,2,39,2,416,5,11,3,16,24,3